// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.Data.DAL;

#nullable disable

namespace TMS.Data.Migrations
{
    [DbContext(typeof(TMSDbContext))]
    [Migration("20260203193217_AddSortOrder")]
    partial class AddSortOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.Data.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SortOrder");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The foundation of every strong economy. Gather wood, food, and gold to advance through the ages.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 34,
                            Subject = "Build more villagers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protect your villagers from early raids by researching Loom at the Town Center.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 33,
                            Subject = "Research Loom"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monks can heal units and convert enemy soldiers. A powerful conversion can turn the tide of battle.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 32,
                            Subject = "Train monks at monastery"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Famous last words before production deployment. Docker can't save you now.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 31,
                            Subject = "It works on my machine"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Converting enemy units since 1997. Your blue soldier is now my red soldier.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 30,
                            Subject = "Wololoo"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The documentation is a lie. Just like the cake.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 29,
                            Subject = "Review documentation"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Have you tried turning it off and on again?",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 28,
                            Subject = "Fix login bug"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One does not simply update all packages without breaking something.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 27,
                            Subject = "Update NuGet packages"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add unit tests for the TaskService class.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 26,
                            Subject = "Create unit tests"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SELECT * FROM problems WHERE solution = 'more indexes'",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 25,
                            Subject = "Database optimization"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generate Swagger documentation for all endpoints. Include request/response examples and proper descriptions for each parameter.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 24,
                            Subject = "API documentation"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "LGTM 👍 (I definitely read all 500 lines)",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 23,
                            Subject = "Code review"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure GitHub Actions for automated builds and deployments.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 22,
                            Subject = "Setup CI/CD pipeline"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "There are only two hard things in CS: cache invalidation and naming things.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 21,
                            Subject = "Implement caching"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Password123 is not a valid password. Neither is Admin123. Stop it.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 20,
                            Subject = "Security audit"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This code was written by a developer who mass despises the next person reading it.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 19,
                            Subject = "Refactor controllers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Console.WriteLine('here'); Console.WriteLine('here 2'); Console.WriteLine('why is this not working');",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 18,
                            Subject = "Add logging"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Run load tests. Pray to the server gods.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 17,
                            Subject = "Performance testing"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSS is easy they said. It will be fun they said.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 16,
                            Subject = "Mobile responsiveness"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "No backup, no sympathy. - Ancient IT Proverb",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 15,
                            Subject = "Backup strategy"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "catch (Exception ex) { // TODO: handle this later }",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 14,
                            Subject = "Error handling"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Users: 'Make the logo bigger.' Also users: 'Why is everything so cluttered?'",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 13,
                            Subject = "User feedback"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migrate legacy data from the old system to the new database schema. Validate data integrity after migration.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 12,
                            Subject = "Data migration"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Certificate expired 3 days ago. Nobody noticed until Karen from accounting couldn't access her spreadsheets.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 11,
                            Subject = "SSL certificate"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ensure the application meets WCAG 2.1 accessibility standards.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 10,
                            Subject = "Accessibility compliance"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design and implement email templates for user notifications including welcome emails, password resets, and task reminders.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 9,
                            Subject = "Email templates"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Because someone will try to call the API 10,000 times per second. Someone always does.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 8,
                            Subject = "Rate limiting"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Server: 'I'm fine.' Also server: *catches fire*",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 7,
                            Subject = "Health checks"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add support for multiple languages. Start with English and Spanish translations for all user-facing text.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 6,
                            Subject = "Localization"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "It works in my container ¯\\_(ツ)_/¯",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 5,
                            Subject = "Docker setup"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bobby Tables would like to have a word with you.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 4,
                            Subject = "Input validation"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Implement secure session management with proper timeout and refresh mechanisms.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 3,
                            Subject = "Session management"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Big Brother is watching. And by Big Brother, I mean the compliance team.",
                            IsCompleted = true,
                            ModifiedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 2,
                            Subject = "Audit logging"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "v1, v2, v3, v3-final, v3-final-FINAL, v3-final-FINAL-use-this-one",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 1,
                            Subject = "API versioning"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Why is Chrome using 8GB of RAM? Oh wait, that's our app.",
                            IsCompleted = false,
                            ModifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SortOrder = 0,
                            Subject = "Memory profiling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
